### ISSUE TITLE
Ability miscategorization

### ISSUE THREAD

**Issue by DoubleMark** [DoubleMark/SynchroDungeonCrawl#2]
Circle of Economic Inefficiency is listed under Movement, though its category on mouseover is still Wasting Money.

Also, it's not tabbed inwards, unlike the other abilities. Related?

**Comment by cesium12** [comment]
...why yes, they are related. Only the indented ones are actually under Movement. But all categories and uncategorized abilities are sorted together by name, so Triple * and Wasting Money come after Movement. Maybe this is more intuitive...
