### ISSUE TITLE
Log entries are near useless

### ISSUE THREAD

**Issue by cesium12** [DoubleMark/SynchroDungeonCrawl#4]
The JS console prints the log entries it gets from the server. For some reason, the only fields that are ever filled are finalDamage and damageModifiers, even when there are effects and movement going on. You don't even get the source and target units.

**Comment by DoubleMark** [comment]
Whoops. Most of the information they need is on the Action they're attached to, which does *not* get shipped

**Comment by DoubleMark** [comment]
That should be better
