### ISSUE TITLE
Action log logs attempted movement but can't convey collision info

### ISSUE THREAD

**Issue by DoubleMark** [DoubleMark/SynchroDungeonCrawl#5]
Thinking about how to log this makes me weep

**Comment by cesium12** [comment]
So bouncing should... mutate the action... to remove the movement part, and then the log... gets that when it's serialized??? Augh

**Comment by DoubleMark** [comment]
But *which* action? If I have two simultaneous <0, 1>s and I collide at delta <0, 2> and land at <0, 1>, an arbitrary one has it movement part removed?

aaaaaahh

**Comment by cesium12** [comment]
That's not how bouncing works. You land on your original square, because if you have simultaneous (0, 1) and (0, 2) but bounce at the total (0, 3), picking whether you land on delta (0, 1) or (0, 2) is a violation of simultaneity.

**Comment by DoubleMark** [comment]
Right. OK maybe that makes this viable.
